### ISSUE TITLE
Outputs UTF-8 characters on LATIN1 terminals

### ISSUE THREAD

**Issue by h3xx** [thiderman/doge#55]
Script does not do appropriate checking of terminal LC_CTYPE locale to test whether the terminal can accept UTF-8 characters. This results in corrupt output.

Suggestion: Transform strings into acceptable character set before outputting.

Steps to reproduce:

    $ LANG=en_US LC_CTYPE=en_US rxvt -e bash -c 'doge;read'

OR

    $ LANG=en_US LC_CTYPE=en_US xterm -e bash -c 'doge;read'

Results in:

![xterm](https://cloud.githubusercontent.com/assets/615684/11923031/f79f6288-a762-11e5-9c82-64373fa07f61.png)

**Comment by thiderman** [comment]
Haha, that looks fun.

However, there is already [some code handling](https://github.com/thiderman/doge/blob/master/doge/core.py#L481-L487) non-UTF-8 cases. I am not sure why this isn't triggering for you, but it sure is for me when I run the snippets you specified.

Have you encountered this problem on a real-life machine or were you just mucking around with running non-UTF-8 stuff?

Cheers for finding inconsistent behavior anyway!

**Comment by h3xx** [comment]
>Have you encountered this problem on a real-life machine or were you just mucking around with running non-UTF-8 stuff?

I ran it on the system and terminal I always use, using the configuration I use for pretty much all my computing.

The Python version I ran it under is 2.7.11. I know Python 2 has different string encoding handling than Python 3, so that may be the cause of it.
