### ISSUE TITLE
ubuntu fail. very sad.

### ISSUE THREAD

**Issue by pantsandsocks** [thiderman/doge#61]
How to install and run on a debian distro such as ubuntu?

I installed it through pip. There were no errors, but when I run doge nothing happens.

I am using uxrvt-unicode for my terminal. Attached is a screenshot.

![2018-02-26-234230_1680x1050_scrot](https://user-images.githubusercontent.com/36874072/36710937-de9dd866-1b4e-11e8-940c-b9409b8b0742.png)

**Comment by thiderman** [comment]
`wow.py` is just a library and cannot be executed like that. When pip install the package, the `doge` command should have been put in `/usr/local/bin` or equivalent. As such, just running `doge` should run the script and give you the output. Does that work?

**Comment by pschfr** [comment]
I can't get it to run either, and it's not in `/usr/local/bin`. Any ideas?

**Comment by pschfr** [comment]
Ah! I just got it to work by putting `sudo -H` before `pip install doge`!

**Comment by pschfr** [comment]
New pull request for this in #63

**Comment by ShebaDoge** [comment]
How about the thing everyone hates: chrome os?
